display:
  default:
    display_options:
      empty:
        area:
          content:
            value: "<div class=\"wrapper\">\r\n<div class=\"span-col-12\">\r\n<h2>Unable to find information matching your search.</h2>\r\n\r\n<p>We're sorry! We'd like to help you find what you are looking for. Please try again with a different term, review our <a href=\"/customer-resources/faq\">FAQs</a> for answers to common questions, or <a href=\"/contact-us\">contact our Customer Support team</a>.</p>\r\n</div>\r\n</div>\r\n"
            format: full_html
      filters:
        title:
          expose:
            placeholder: 검색
        field_resource_type_target_id:
          expose:
            label: '자료 유형'
        field_shared_service_type_target_id:
          expose:
            label: 서비스
        field_shared_country_target_id:
          expose:
            label: 시장
