<?php

/**
 * @file
 * Block content template functionality.
 *
 * This was originally taken from:
 * https://github.com/swentel/block_content_template
 * It has been modified and includes bug fixes.
 *
 * @see: https://www.drupal.org/project/drupal/issues/2704331
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function ul_block_theme() {
  return [
    'block_content' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view_alter() for block_content.
 */
function ul_block_block_content_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (isset($build['_layout_builder']) || isset($entity->view) || isset($entity->_referringItem)) {
    $build['#theme'] = 'block_content';
  }
}

/**
 * Preprocess function for block content template.
 */
function template_preprocess_block_content(&$variables) {
  $variables['content'] = [];
  if (isset($variables['elements']['_layout_builder'])) {
    $variables['content'][] = $variables['elements']['_layout_builder'];
  }
  else {
    $content = [];
    $content['#block_content'] = $variables['elements']['#block_content'];
    foreach (Element::children($variables['elements']) as $key) {
      $content[$key] = $variables['elements'][$key];
    }
    $variables['content'] = $content;
  }

  // Remove quick edit as it doesn't make sense here. It also points to the view
  // for instance, which doesn't make sense at all.
  if (isset($variables['attributes']['data-quickedit-entity-id'])) {
    unset($variables['attributes']['data-quickedit-entity-id']);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ul_block_theme_suggestions_block_content(array $variables) {
  $suggestions = [];
  $block_content = $variables['elements']['#block_content'];

  $suggestions[] = 'block_content__' . $block_content->bundle();
  $suggestions[] = 'block_content__' . $block_content->id();

  return $suggestions;
}
