_core:
  default_config_hash: vOaSYBgSyTzn8_p0MSY8B-ygp9V0Nc6qnX0vy9KYGeo
extlink_use_external_js_file: true
extlink_exclude_admin_routes: true
extlink_target: false
extlink_target_no_override: false
extlink_nofollow: false
extlink_noreferrer: true
extlink_follow_no_override: false
extlink_subdomains: true
extlink_alert: true
extlink_alert_text: ''
extlink_exclude: '([.]*)'
extlink_include: '(emergobyul\.com|emergo-[dev|prod|stage]|kvausa\.com/consulting)'
extlink_class: ext
extlink_label: '(link is external)'
extlink_img_class: false
extlink_css_exclude: ''
extlink_css_explicit: ''
extlink_mailto_class: mailto
extlink_mailto_label: '(link sends email)'
extlink_use_font_awesome: false
extlink_font_awesome_classes:
  links: 'fa fa-external-link'
  mailto: 'fa fa-envelope-o'
extlink_icon_placement: after
whitelisted_domains: {  }
