display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'Sort by'
      filters:
        langcode:
          expose:
            label: Language
  page_1:
    display_title: 页
