display:
  default:
    display_title: Master
    display_options:
      fields:
        bundle:
          label: Type
      exposed_form:
        options:
          exposed_sorts_label: 'Sort by'
      empty:
        area_text_custom:
          content: 'No content available.'
      filters:
        bundle:
          expose:
            label: Type
        langcode:
          expose:
            label: Language
