display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'Sort by'
      fields:
        type:
          label: Type
  page_2:
    display_options:
      fields:
        type:
          label: Type
  page_3:
    display_options:
      fields:
        type:
          label: Type
  page_4:
    display_options:
      fields:
        type:
          label: Type
