display:
  default:
    display_options:
      fields:
        file_extension:
          label: Source
        language:
          label: Language
      exposed_form:
        options:
          exposed_sorts_label: 'Sort by'
      filters:
        language:
          expose:
            label: Language
