display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'Sort by'
      empty:
        area_text_custom:
          content: 'No media available.'
      filters:
        langcode:
          expose:
            label: Language
  page:
    display_title: Página
