_core:
  default_config_hash: 9YPlBuinIKLe5jVEf-aIhZvKFn77i18yD4CrNR0BbVQ
buttons_size: 32
additional_html: "<span class=\"share\">Share:</span>\r\n<a class=\"a2a_button_linkedin\">\r\n<span class=\"icon icon-linkedin\"></span>\r\n</a>\r\n<a class=\"a2a_button_twitter\">\r\n<span class=\"icon icon-twitter\"></span>\r\n</a>\r\n<a class=\"a2a_button_facebook\">\r\n<span class=\"icon icon-facebook\"></span>\r\n</a>\r\n<a class=\"a2a_button_email\">\r\n<span class=\"icon icon-mail\"></span>\r\n</a>"
additional_css: ''
additional_js: ''
universal_button: none
custom_universal_button: ''
universal_button_placement: before
entities:
  media: 0
  node: 1
  comment: 1
  block_content: 0
  file: 0
  redirect: 0
  search_api_task: 0
  shortcut: 0
  taxonomy_term: 0
  ul_alert: 0
  crc_asset: 0
  ul_legal_hold: 0
  user: 0
  menu_link_content: 0
  paragraph: 0
  path_alias: 0
no_3p: true
