_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  advagg: 0
  animated_gif: 0
  auto_entitylabel: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor5: 0
  ckeditor_config: 0
  ckeditor_templates: 0
  cm_submit: 0
  cm_workbench: 0
  color_field: 0
  colorbutton: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  config_update: 0
  content_moderation: 0
  content_translation_redirect: 0
  contextual: 0
  crop: 0
  csp: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  default_content: 0
  dblog: 0
  diff: 0
  dropdown_language: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  entity_usage: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  features: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  globallink: 0
  google_cse: 0
  google_json_api: 0
  google_tag: 0
  graphql: 0
  help: 0
  history: 0
  http_cache_control: 0
  image: 0
  image_effects: 0
  image_widget_crop: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  languagefield: 0
  link: 0
  locale: 0
  maxlength: 0
  media: 0
  media_entity_file_replace: 0
  media_library: 0
  media_responsive_thumbnail: 0
  menu_block: 0
  menu_link_attributes: 0
  menu_trail_by_path: 0
  menu_ui: 0
  metatag: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_drupal: 0
  migrate_file: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  options: 0
  panelbutton: 0
  pantheon_advanced_page_cache: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  path_redirect_import: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  redis: 0
  responsive_image: 0
  rest: 0
  rh_node: 0
  rh_taxonomy: 0
  robotstxt: 0
  role_delegation: 0
  scheduled_transitions: 0
  scheduler: 0
  search: 0
  search_api: 0
  search_api_db: 0
  seckit: 0
  serialization: 0
  shield: 0
  shortcut: 0
  simple_sitemap: 0
  smtp: 0
  social_media_links: 0
  social_media_links_field: 0
  sophron: 0
  svg_image_field: 0
  svg_image_field_media_bundle: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_import: 0
  telephone: 0
  text: 0
  tmgmt: 0
  tmgmt_content: 0
  tmgmt_file: 0
  tmgmt_language_combination: 0
  tmgmt_local: 0
  tmgmt_locale: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  twig_xdebug: 0
  typed_data: 0
  ul_alerts: 0
  ul_base_config: 0
  ul_base_profile: 0
  ul_block: 0
  ul_chat: 0
  ul_crc: 0
  ul_crc_asset: 0
  ul_crop_image: 0
  ul_datalayer: 0
  ul_disable_content: 0
  ul_duplicate_aliases: 0
  ul_editorial: 0
  ul_enterprise_default_content: 0
  ul_experience_hub: 0
  ul_gmap: 0
  ul_google_json_api: 0
  ul_haas: 0
  ul_json: 0
  ul_legal_hold: 0
  ul_marketo: 0
  ul_media: 0
  ul_no_translation_fields: 0
  ul_pathauto: 0
  ul_private_event: 0
  ul_report: 0
  ul_revision_log: 0
  ul_salesforce: 0
  ul_tools: 0
  ul_trustarc: 0
  ul_twig: 0
  ultimate_cron: 0
  user: 0
  vde_drush: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wistia: 0
  view_custom_table: 0
  view_mode_selector: 0
  views_data_export: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  viewsreference: 0
  webp: 0
  workflows: 0
  entity_update: 1
  imagemagick: 1
  menu_link_content: 1
  page_manager: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  ul_cou_fix: 999
  ul_enterprise_profile: 1000
theme:
  stable: 0
  classy: 0
  ul_base_theme: 0
  ul_enterprise_theme: 0
  claro: 0
  ul_com_theme: 0
  ul_anz_theme: 0
profile: ul_enterprise_profile
