_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - media
track_enabled_source_entity_types:
  - node
  - block_content
  - paragraph
  - editor
track_enabled_target_entity_types:
  - media
track_enabled_plugins:
  - media_embed
  - entity_reference
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types:
  - media
delete_warning_message_entity_types: {  }
usage_controller_items_per_page: 25
