container_id: ''
path_toggle: 'exclude listed'
path_list: |-
  /admin*
  /batch*
  /node/add*
  /node/*/edit
  /node/*/delete
  /user/*/edit*
  /user/*/cancel*
role_toggle: 'exclude listed'
role_list:
  - null
status_toggle: 'exclude listed'
status_list: |-
  403
  404
compact_snippet: true
include_file: true
rebuild_snippets: true
debug_output: false
data_layer: dataLayer
include_classes: false
whitelist_classes: |-
  google
  nonGooglePixels
  nonGoogleScripts
  nonGoogleIframes
blacklist_classes: |-
  customScripts
  customPixels
include_environment: false
environment_id: ''
environment_token: ''
_core:
  default_config_hash: UyNPbddlLO3s8kwBAYs5ubS74V4uBRmWxfrE9yEGeGM
