_core:
  default_config_hash: 0dWNLayAygP3jiVgvA3lyQo266plRZ5Z8hn_sP1Kv5g
cache:
  http:
    s_maxage: 0
    404_max_age: 0
    302_max_age: 0
    301_max_age: 0
    5xx_max_age: 0
    stale_while_revalidate: 0
    stale_if_error: 0
    vary: ''
