settings:
  library_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.js'
  css_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.css'
  crop_preview_image_style: media_library
  crop_list: {  }
  crop_types_required: {  }
  warn_multiple_usages: false
  show_default_crop: false
  show_crop_area: false
  notify_apply: true
  notify_update: true
