entity_type_groups:
  node:
    campaign_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    event:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    help:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    homepage:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    hub:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    knowledge:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    landing_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    news:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    offering:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    person:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    resource:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    tool:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
