_core:
  default_config_hash: ceCx5XZ_ay1Mxcv-sB95U_fBKoVkpvo8RaQiwutSZLI
content: |
  #
  # robots.txt
  #
  # This file is to prevent the crawling and indexing of certain parts
  # of your site by web crawlers and spiders run by sites like Yahoo!
  # and Google. By telling these "robots" where not to go on your site,
  # you save bandwidth and server resources.
  #
  # This file will be ignored unless it is at the root of your host:
  # Used:    http://example.com/robots.txt
  # Ignored: http://example.com/site/robots.txt
  #
  # For more information about the robots.txt standard, see:
  # http://www.robotstxt.org/robotstxt.html

  User-agent: *

  # CSS, JS, Images
  # Directories
  # Files

  # Paths (clean URLs)
  Disallow: /filter/tips
  Disallow: /node/*
  Disallow: */node/*
  Disallow: /search/
  Disallow: /user/register/
  Disallow: /user/password/
  Disallow: /user/login/
  Disallow: /user/logout/
  Disallow: /contact-us/*
  Disallow: /newsletter-signup/*
  Disallow: /event-signup/*
  Disallow: /request-demo/*
  Disallow: /contact-sales/*
  Disallow: /media/oembed
  Disallow: /*/media/oembed
  Disallow: */event-signup
  Disallow: */newsletter-signup
  Disallow: */sales-inquiry
  Disallow: */sales-inquiries

  # Paths (no clean URLs)
  Disallow: /index.php/filter/tips
  Disallow: /index.php/search/
  Disallow: /index.php/user/password/
  Disallow: /index.php/user/register/
  Disallow: /index.php/user/login/
  Disallow: /index.php/user/logout/
  Disallow: /index.php/media/oembed
  Disallow: /index.php/*/media/oembed
  Disallow: /index.php/event-signup
  Disallow: /index.php/*/event-signup
  Disallow: /index.php/newsletter-signup
  Disallow: /index.php/*/newsletter-signup
  Disallow: /index.php/sales-inquiry
  Disallow: /index.php/*/sales-inquiry
  Disallow: /index.php/sales-inquiries
  Disallow: /index.php/*/sales-inquiries
