shield_enable: false
credential_provider: shield
credentials:
  shield: null
allow_cli: true
debug_header: false
unset_basic_auth_headers: true
print: ''
method: 0
paths: "/acquia-contenthub/*\r\n/acquia_contenthub/*"
allowlist: ''
domains: ''
