_core:
  default_config_hash: vFARRSP9-YgEArfDNYmRSg0cNFOgZPxqziffIalgLbU
max_links: 2000
cron_generate: false
cron_generate_interval: 0
generate_duration: 10000
remove_duplicates: true
skip_untranslated: true
xsl: true
base_url: ''
default_variant: default
custom_links_include_images: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - taxonomy_term
  - menu_link_content
batch_process_limit: 1500
