_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
smtp_on: true
smtp_host: smtp.mailgun.org
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: false
smtp_timeout: 30
smtp_username: uldrupal@mg.ul.com
smtp_password: ''
smtp_from: no-reply-www@mg.ul.com
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_reroute_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
