last_interests:
  id: last_interests
  display: last_interests
  last_interests:
    - 'Access Control'
    - 'Additive Manufacturing'
    - 'Adjunct Services (UL-ES, FL-QA, BSAI, Simmons QA)'
    - 'Advisory Services'
    - Aerospace/Defence/Rail
    - 'Agile and Scaled Agile Training'
    - 'Air Conditioner'
    - 'Air Ducts & Systems'
    - 'Alarm Certificates'
    - 'Alarm Certificate Service'
    - 'Alarm Company and Monitoring Station Certification Services'
    - 'Animal Care and Control Appliances'
    - 'Appliance Wiring Material (AWM)'
    - 'Appliances / Lighting'
    - 'Application Lifecycle Management'
    - Architects/Designers
    - 'Architecture – Commercial'
    - 'Architecture – Mixed Use'
    - 'Architecture – Residential'
    - 'Audio/Visual Equipment'
    - 'Audio & Video Carts and Stands'
    - Automotive
    - 'Automotive Architecture (Autosar)'
    - 'Automotive Component Testing & Validation'
    - 'Automotive Cybersecurity'
    - 'Automotive EMC and IOP'
    - 'Automotive Functional Safety'
    - 'Automotive Integrated Development'
    - 'Automotive Spice Training'
    - 'Automotive Systems and Software'
    - 'Automotive Training'
    - 'Autonomy Safety'
    - 'Banking and Finance'
    - 'Batteries / Charging'
    - 'BE Digital'
    - 'BP Services'
    - 'Building & Construction'
    - 'Building & Construction FUS/Specialty'
    - 'Building Envelope'
    - 'Building Envelope Advisory'
    - 'Building Envelope Products'
    - 'Building Envelope Testing'
    - 'Building Inspection Services'
    - 'Building Inspections'
    - 'Building Material & System'
    - 'Building Owners/Occupiers/Managers'
    - 'Building Products'
    - 'Building Products (Commodities)'
    - 'Building Quality & Compliance'
    - 'Building Quality & Compliance FUS/Specialty'
    - 'Building Security Products'
    - 'Building Systems (Field Constructed Assemblies)'
    - 'Cabinets / Vanities'
    - 'Camera and Security System'
    - 'Cannabidiol (CBD)'
    - 'Carbon Management and Reporting'
    - CCC/CQC
    - Chemical/Biological
    - 'Chemical Policy Development & Management'
    - 'Chemical Policy Management Software'
    - 'Chemical R&D Software'
    - 'Chemical Registration'
    - 'Chemical Regulatory Advisory Services'
    - 'Chemical Regulatory Database (LoLi)'
    - 'Chemical Regulatory Training'
    - 'Chemical Toxicology'
    - Children’s
    - 'Circuit Protection'
    - 'Cleaning Products'
    - 'CMMI Training'
    - 'Coatings and Liquids'
    - 'Commercial Cooking'
    - 'Commercial Furniture'
    - 'Compliance Reporting'
    - 'Component Products'
    - 'Components and Accessories for W&C'
    - 'Components (Wire & Cable)'
    - 'Compounds for use in W&C'
    - Composites
    - 'Conformity Advisory'
    - 'Connectivity and Wireless'
    - 'Construction Materials (adhesives, insulation, sealant)'
    - 'Construction Equipment'
    - 'Construction – Commercial'
    - 'Construction – Design Build'
    - 'Construction – Residential'
    - 'Consumer and Commercial Robots'
    - 'Consumer Electronics'
    - 'Consumer Products - Other'
    - Contractors
    - Controls
    - 'Copper Wire'
    - 'Critical Systems Consulting'
    - 'Critical Systems Engineering Services'
    - 'Critical Systems Merchandise'
    - 'Critical Systems Product'
    - 'Critical Systems Training'
    - 'CRS - Private Label'
    - 'CRS - Retail'
    - 'Custom Course Development'
    - 'Data Analytics'
    - 'Data Centers'
    - 'Device Security'
    - 'Dietary Supplements'
    - 'Digital Health'
    - Distributor
    - 'Door Operators & Systems'
    - Ducts
    - 'e-Cigarettes and Vaporizers'
    - E-Mobility
    - E-Toys
    - 'EASA (North America Service Offering)'
    - Educational
    - 'Electrical Distribution'
    - 'Electrical Insulation Materials and Systems'
    - 'Electronic Controls'
    - 'Electronic W&C'
    - 'Equipment Compliance'
    - 'Emergency Vehicles'
    - 'Emergency Voice Evacuation Systems'
    - 'EHS Online Training'
    - 'EMC Testing'
    - Energy
    - 'Energy Efficiency'
    - 'Energy Systems'
    - 'Energy Systems & E-Mobility'
    - 'Environment – Other'
    - 'Environmental Claims Products'
    - 'Environmental Simulation & Dynamics Testing'
    - 'ESG Advisory'
    - 'ESG Assurance'
    - 'ESG Reporting'
    - 'ESG Reporting for Property'
    - Everclean
    - 'Exposure Water'
    - 'Extinguishing Systems'
    - 'Face Masks'
    - FACP
    - 'Facility - High Tech'
    - 'Facility Management'
    - 'Facility Safety'
    - 'Factory Control Systems'
    - Fans
    - 'Fiber Optic Cable and Components'
    - 'Field Connect'
    - 'Field Evaluation'
    - 'Field Program'
    - 'Field Services'
    - 'Filament Wound Tubing'
    - 'Fire & Smoke Detection'
    - 'Fire and Emergency Vehicles'
    - 'Fire Alarm Control & Communication Equipment'
    - 'Fire Alarm Control Products & Systems'
    - 'Fire Barrier Management'
    - 'Fire Containment'
    - 'Fire Containment Products'
    - 'Fire Detection'
    - 'Fire Equipment Services Factory'
    - 'Fire Equipment Services In-Service'
    - 'Fire Extinguishers'
    - 'Fire Fighting Foam'
    - 'Fire Main Equipment'
    - 'Fire Pumps'
    - 'Fire Resistive'
    - 'Fire Resistive Products'
    - 'Fire Safety'
    - 'Fire Safety & Security'
    - 'Fire Safety & Security FUS/Specialty'
    - 'Fire Stops & Joints'
    - 'Fire Stops & Containment Inspection'
    - 'Fire Suppression'
    - 'Fire Suppression Products'
    - 'Firefighter Rescue Tools'
    - 'First Responder/Industrial'
    - 'FL QA'
    - 'Floor Care Appliances'
    - 'Fluid Thermal Management Testing'
    - Foam
    - 'Foam Equipment'
    - 'Food & Beverage'
    - 'Furniture Components'
    - 'Furniture Test Equipment'
    - 'Gaming Equipment'
    - 'Garment Care Appliances'
    - 'Gaskets and Seals'
    - 'General Building Products'
    - 'General Building Systems'
    - 'General Furniture'
    - 'General Merchandise & Hardlines'
    - 'Government and Federal'
    - 'GRI Reporting'
    - 'Grooming Appliances'
    - Harnesses
    - 'Hazardous Locations'
    - 'Hazard Communication Software'
    - Healthcare
    - 'Healthcare and eHealth'
    - 'Healthcare / Institutional Furniture'
    - 'Healthcare Product Testing & Certification'
    - 'Healthy Buildings'
    - 'Heaters & Heating Equipment'
    - Heating
    - 'Heating Appliances'
    - 'Hearing Protection'
    - 'High Speed Wired Connectivity'
    - 'High Tech Components'
    - 'High Tech Power Supplies'
    - 'Home Comfort Appliances'
    - 'Home Comfort Appliances - Vaporizers'
    - 'Home Environment Appliances'
    - 'HOMER Front Utility-Scale Hybrid Power Optimization'
    - 'HOMER Grid Distributed Generation Optimization'
    - 'HOMER Pro Standalone Microgrid Optimization'
    - Homologation
    - Hospitality
    - 'Household & Industrial Cleaning'
    - Hydrants
    - 'Incident/Audit Management Software'
    - 'Industry 40'
    - 'Industry Association'
    - 'Industrial Functional Safety'
    - 'Information Technology Equipment'
    - 'Industrial Electronics'
    - 'Industrial Systems and Software'
    - 'Industrial W&C'
    - 'Initiating and Indicating Devices'
    - 'IOT Smart Cars'
    - 'IOT Smart Homes'
    - 'IOT Smart Phones'
    - 'IOT Systems and Software'
    - 'IOT Wearables'
    - 'Intrusion Detection'
    - INMETRO
    - 'Jewelry & Watches'
    - 'Kitchen Appliances'
    - Laboratory
    - Ladders
    - 'Ladders, Scaffoldings & Hoists'
    - 'Lead Generation & Digital Advertising'
    - 'Learning & Talent Management Systems'
    - 'LED Luminaires'
    - 'LED Portable Luminaires'
    - 'Life Safety & Security'
    - 'Life Safety System'
    - 'Life Sciences Online Training'
    - Lighting/Luminaires
    - 'Lighting Lamp'
    - 'Lighting Component'
    - Locks
    - LPS
    - 'Major Appliances'
    - 'Manufacturer – Building Products'
    - 'Manufacturer – Chemicals'
    - 'Manufacturer – Consumer Goods'
    - 'Market Access - Safety'
    - 'Market Access - Wireless'
    - 'Marking and Labeling'
    - 'Massage and Exercise Equipment'
    - 'Materials and Process'
    - 'Materials & Components Search Engines'
    - 'Materials Search'
    - 'Mattresses and Bedding'
    - Mechanical
    - 'Medical Billing Software'
    - 'Medical Cybersecurity'
    - 'Medical Device and Application Training'
    - 'Medical Regulatory Compliance'
    - 'Medical Systems and Software'
    - 'Medical Technologies'
    - 'Metallic Cable'
    - Micromobility
    - 'Mobile and Telecom'
    - 'Mobile and Telecommunications Products'
    - 'Modular Inspection'
    - Motors
    - 'N/A - Additive Manufacturing'
    - 'N/A - Appliances'
    - 'N/A - Automotive'
    - 'N/A - Building Materials & Systems'
    - 'N/A - Components'
    - 'N/A - Energy & Power Technologies'
    - 'N/A - Furniture'
    - 'N/A - Functional Safety'
    - 'N/A - Health Sciences'
    - 'N/A - High Tech'
    - 'N/A - HVAC'
    - 'N/A - Information and Communication Technology'
    - 'N/A - Internet of Things'
    - 'N/A - Life Safety & Security'
    - 'N/A - Lighting'
    - 'N/A - Performance Materials'
    - 'N/A - Renewables'
    - 'N/A - Small Appliances'
    - 'N/A - Transaction Security'
    - 'N/A - Water'
    - 'N/A - Wire & Cable'
    - 'Next Gen Communication'
    - 'Non-Clinical Testing'
    - Non-Profit
    - 'Notification Appliances'
    - 'Occupational Health Software'
    - Office
    - 'Offshore Wind Advisory'
    - 'Oil & Gas'
    - 'Opening Protective Products'
    - 'Opening Protective Systems'
    - 'Openwind Plant Design'
    - 'Optical Fiber'
    - 'OTC & Pharmaceuticals'
    - Other
    - 'Outdoor Furniture'
    - Packaging
    - Paints
    - 'Paints and Coatings'
    - 'Payments CSE'
    - 'Payments Tech'
    - 'PCB / PWB / Components'
    - 'Performance Materials'
    - 'Performance Materials Automotive'
    - 'Performance Materials Transportation'
    - 'Performance Testing'
    - 'Personal Care & Beauty'
    - 'Personal Flotation Devices (PFD)'
    - Piping
    - 'Pipings / Fittings'
    - Plastics
    - 'Plumbing Products'
    - 'Pools & Spa'
    - 'Positioning Devices'
    - 'Power Cords'
    - 'Power Supplies (small)'
    - 'Power Supplies - Automotive'
    - 'Power Utility Cables'
    - 'Power W&C'
    - PPE
    - 'PPE FUS/Specialty'
    - 'Premiums, Promotional & Licensed Goods'
    - 'Product Emissions'
    - 'Product Marketing Services'
    - 'Product Performance Benchmarking'
    - 'Product Promotion & Differentiation'
    - 'Product Promotion and Intelligence - Certification'
    - 'Protective Eyewear'
    - 'Protective Footwear'
    - 'Protective Garments'
    - 'Protective Gloves'
    - 'Protective Helmets'
    - PSS
    - 'QMS Certification'
    - 'R&D Decision Support'
    - 'Raw Products'
    - 'RCP - Chemicals'
    - 'RCP - Private Label'
    - 'RCP - Retail'
    - 'Recycled Plastics'
    - 'Real Estate'
    - 'Regulatory Advisory Services & Training'
    - 'Regulatory Compliance & SDS Authoring'
    - 'Regulatory Compliance Training'
    - 'Regulatory Insights & Monitoring'
    - 'Renewable Resource Assessment Platform (RRAP)'
    - 'Renewables - E-Mobility'
    - 'Renewables - Energy Systems'
    - 'Renewables-Plus-Storage Advisory'
    - 'Renewables Assets Monitoring Platform (RAMP)'
    - 'Renewables Resource Maps or Data'
    - 'Rescue Equipment'
    - Residential
    - 'Residential Refrigeration'
    - 'Respiratory Protection'
    - 'Responsible Sourcing'
    - 'Retail and Payments'
    - 'Retail Compliance'
    - 'Retail Fixtures, Displays & Kiosk'
    - 'Retail Software Solutions'
    - 'Retailer – Building Products'
    - 'Retailer – Consumer Goods'
    - 'Retailer – Furniture'
    - Roofing
    - 'Roofing Materials'
    - 'Roofing Products'
    - Ropes
    - 'Software Training'
    - 'Stages and Process Management'
    - 'Smart Building'
    - 'System Manufacturers'
    - 'Safety Consulting Services'
    - 'Supplier Audit Services'
    - 'Smart Healthcare'
    - 'Smart Mobility'
    - 'Smart Payments'
    - 'Specialty Lamp Control Equipment'
    - 'Specialty Luminaires'
    - 'Specialty Portable Luminaires'
    - 'Security Cameras'
    - 'Security Containers'
    - 'Security Equipment'
    - 'Smoke / Fire / Gas Detection Products'
    - 'Smoke Control Systems'
    - Sprinklers
    - 'Sprinklers, Valves, Warehouse'
    - 'Specialty Appliances'
    - 'Switches and Protectors'
    - 'Switching Devices'
    - 'Safety Data Sheet (SDS) Authoring'
    - 'Supply Chain Management Software'
    - 'Supply Chain Stewardship'
    - Solar
    - 'Sustainability Management and Reporting'
    - 'Solar Advisory'
    - 'Smart Buildings'
    - 'Seasonal Products'
    - 'Tape, Tubing, Sleeving'
    - 'Targeted Training'
    - 'Technical Competency Development/Management'
    - 'Technical Datasheet Solutions'
    - 'Textiles, Apparel, & Footwear'
    - Tools
    - 'Toys & Juvenile Products'
    - 'Traditional Payments'
    - Training
    - 'Transit and Transportation'
    - 'Transport & Dangerous Goods'
    - Transportation
    - 'UL ES'
    - 'Variation Notice (VN)'
    - Ventilation
    - 'Virtual/Augmented/Mixed Reality'
    - 'Vulcanized Fiber'
    - 'Waste Management and Reporting'
    - 'Water Mist Systems'
    - 'Water Treatment Chemicals'
    - 'Wearable Electronics'
    - 'Wiring Devices'
    - Wind
    - 'Wind - Certification'
    - 'Wind - Electrical Characteristics'
    - 'Wind - Grid Codes'
    - 'Wind - Mechanical Loads'
    - 'Wind - Power Performance'
    - 'Wind - R&D'
    - 'Wind - Type Testing'
    - 'Wind Advisory'
    - 'Wind or Solar Forecasting'
    - 'Wind Products & Certification'
    - 'Wind TIC - Certification and Grid Codes'
    - 'Wind TIC - Electrical Characteristics'
    - 'Wind TIC - Mechanical Loads'
    - 'Wind TIC - Power Performance'
    - 'Wind Turbine Digital Inspection Platform'
    - 'Windographer Data Analysis'
    - 'Windnavigator Wind Speed Data Platform'
    - 'Wire & Cable'
    - 'Wire & Cable Design Software'
    - 'Wire & Cable Manufacturing Software'
    - 'Wire & Cable Transportation'
    - 'Wiring Harnesses'
    - 'General Contact'
    - 'General Contact - Software'
