display:
  default:
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'Sort by'
      fields:
        type:
          label: Source
  page_1:
    display_title: Pagina
