display:
  default:
    display_options:
      filters:
        field_shared_industry_target_id:
          expose:
            label: Branche
        field_event_type_target_id:
          expose:
            label: Veranstaltungstyp
        title:
          expose:
            placeholder: Suche
      empty:
        area:
          content:
            value: "<div class=\"wrapper\">\r\n<div class=\"span-col-12\">\r\n<h2>There are currently no upcoming events scheduled. Please check back at a later time.</h2>\r\n</div>\r\n</div>\r\n"
            format: full_html
