_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - system.site
  - language.negotiation
  - 'language.entity.*'
  - 'ul_samlauth.*'
  - 'ul_crc.*'
  - 'samlauth.*'
  - 'system.theme:default'
  - 'google_tag.*'
  - 'config_split.config_split.*:status'
  - 'system.action.book_add_node_action.*'
  - 'system.action.book_remove_node_action.*'
  - ~views.view.content_domain_reference
  - ~views.view.crc_asset_search
  - ~views.view.file_selector
  - ~views.view.image_selector
  - ~views.view.popular_content
  - ~views.view.search_results
  - ~views.view.search_results_featured_result
  - ~views.view.redirect
  - 'block.block.*'
  - '~block.block.claro*'
  - ~block.block.claro_breadcrumbs
  - ~block.block.claro_content
  - ~block.block.claro_help
  - ~block.block.claro_local_actions
  - ~block.block.claro_messages
  - ~block.block.claro_page_title
  - ~block.block.claro_primary_local_tasks
  - ~block.block.claro_secondary_local_tasks
  - ~block.block.claro_footer
  - ~block.block.claro_sitebrandingfooter
  - ~block.block.claro_zendeskwidget
  - ~block.block.claro_ul_guidelines_main_menu
  - ~block.block.claro_childnavigation
  - ~block.block.claro_search_results_search_block
  - ~block.block.claro_ul_guidelines_branding
  - ~block.block.claro_ulguidelinesbookmobilenavigation
  - ~block.block.claro_temporarylazyloadfix
  - ~block.block.claro_ulguidelinesbooknavigation
  - ~block.block.claro_useraccountmenu
  - ~block.block.claro_ul_guideslines_messages
  - ~block.block.claro_2019holidayalert
  - ~block.block.claro_ul_guidelines_help
  - ~block.block.claro_ul_guidelines_local_actions
  - ~block.block.claro_ul_guidelines_local_tasks
  - ~block.block.claro_ul_guidelines_content
  - ~block.block.claro_ul_guidelines_messages
  - ~block.block.claro_shareformblock
  - ~block.block.claro_feedbackformblock
  - ~block.block.claro_views_block__ul_user_info_block_1
ignored_config_collections: {  }
enable_export_filtering: true
