_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  book: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor5: 0
  ckeditor_templates: 0
  cm_submit: 0
  cm_workbench: 0
  colorbutton: 0
  comment: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_update: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  csp: 0
  ctools: 0
  datalayer: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  externalauth: 0
  features: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  language: 0
  link: 0
  mailgun: 0
  mailsystem: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  node_view_permissions: 0
  options: 0
  panelbutton: 0
  pantheon_advanced_page_cache: 0
  path: 0
  path_alias: 0
  r4032login: 0
  rdf: 0
  redirect: 0
  redis: 0
  rest: 0
  robotstxt: 0
  samlauth: 0
  search: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  shield: 0
  shortcut: 0
  simple_sitemap: 0
  smtp: 0
  social_media_links: 0
  social_media_links_field: 0
  statistics: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  ul_base_config: 0
  ul_base_profile: 0
  ul_crc: 0
  ul_crc_asset: 0
  ul_crc_user: 0
  ul_guidelines_forms: 0
  ul_guidelines_navigation: 0
  ul_guidelines_search: 0
  ul_guidelines_share: 0
  ul_guidelines_zendesk: 0
  ul_media: 0
  ul_samlauth: 0
  ultimate_cron: 0
  user: 0
  views_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  ul_guidelines_profile: 1000
theme:
  stable: 0
  classy: 0
  ul_base_theme: 0
  ul_guidelines_theme: 0
  claro: 0
  stark: 0
  ul_brandhub_theme: 0
profile: ul_guidelines_profile
