_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
smtp_on: true
smtp_host: smtp.mailgun.org
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: smtp@mg.ul.com
smtp_password: ''
smtp_from: no-reply@hub.ul.com
smtp_fromname: 'UL Guidelines'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
